//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Buscador_Personalizado.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EstudiantesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EstudiantesEntities object using the connection string found in the 'EstudiantesEntities' section of the application configuration file.
        /// </summary>
        public EstudiantesEntities() : base("name=EstudiantesEntities", "EstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EstudiantesEntities object.
        /// </summary>
        public EstudiantesEntities(string connectionString) : base(connectionString, "EstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EstudiantesEntities object.
        /// </summary>
        public EstudiantesEntities(EntityConnection connection) : base(connection, "EstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Estudiantes> Tbl_Estudiantes
        {
            get
            {
                if ((_Tbl_Estudiantes == null))
                {
                    _Tbl_Estudiantes = base.CreateObjectSet<Tbl_Estudiantes>("Tbl_Estudiantes");
                }
                return _Tbl_Estudiantes;
            }
        }
        private ObjectSet<Tbl_Estudiantes> _Tbl_Estudiantes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Estudiantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Estudiantes(Tbl_Estudiantes tbl_Estudiantes)
        {
            base.AddObject("Tbl_Estudiantes", tbl_Estudiantes);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EstudiantesModel", Name="Tbl_Estudiantes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Estudiantes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Estudiantes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Tbl_Estudiantes CreateTbl_Estudiantes(global::System.Int32 id)
        {
            Tbl_Estudiantes tbl_Estudiantes = new Tbl_Estudiantes();
            tbl_Estudiantes.Id = id;
            return tbl_Estudiantes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaterno
        {
            get
            {
                return _ApellidoPaterno;
            }
            set
            {
                OnApellidoPaternoChanging(value);
                ReportPropertyChanging("ApellidoPaterno");
                _ApellidoPaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidoPaterno");
                OnApellidoPaternoChanged();
            }
        }
        private global::System.String _ApellidoPaterno;
        partial void OnApellidoPaternoChanging(global::System.String value);
        partial void OnApellidoPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidoMaterno
        {
            get
            {
                return _ApellidoMaterno;
            }
            set
            {
                OnApellidoMaternoChanging(value);
                ReportPropertyChanging("ApellidoMaterno");
                _ApellidoMaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidoMaterno");
                OnApellidoMaternoChanged();
            }
        }
        private global::System.String _ApellidoMaterno;
        partial void OnApellidoMaternoChanging(global::System.String value);
        partial void OnApellidoMaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Promedio
        {
            get
            {
                return _Promedio;
            }
            set
            {
                OnPromedioChanging(value);
                ReportPropertyChanging("Promedio");
                _Promedio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Promedio");
                OnPromedioChanged();
            }
        }
        private global::System.String _Promedio;
        partial void OnPromedioChanging(global::System.String value);
        partial void OnPromedioChanged();

        #endregion

    
    }

    #endregion

    
}
